.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PRECIOUS\-JSON" "7" "May 2012" "" ""
.
.SH "NAME"
\fBprecious\-json\fR \- tells precious what is wanted
.
.SH "WHAT"
Data format / expectations about what goes in and out of \fBprecious\fR\.
.
.SS "e\.g\."
A precious sample of valid json input\.
.
.IP "" 4
.
.nf

{ "utc": "1974\-06\-30T21:45:00\.000Z"
, "stuff": [[0], [0, 1], null]
}
.
.fi
.
.IP "" 0
.
.P
This query is about where on the ecliptic (0) the Sun (0) and Moon (1) would be found, given a moment of time\.
.
.SS "In"
Specification of the request / instructions (or defaults) \- the \fBprecious\fR can take\.
.
.P
A relative or absolute path to the Swiss Ephemeris data files\.
.
.P
We get "json" by default anyway (same as null)\. A bit more human\-readable output is "pprint"\. Even better is Eden\'s command line interface\.
.
.P
The kind of stuff to be returned, or null, or empty array(s) [] \- mean all the same default equivalent\. The first array \fB[0, 3]\fR respectively yields ecliptic position and speed for each item of interest\. These map directly to results of the \fBswe\.calc_ut\fR function\. The second array contains the main kind of things \- returned with key of \'1\'\. The third array contains the minor kind of things \- offset by 10,000 and returned with key of \'2\'\.
.
.P
Undefined (or null) \fIutc\fR time \- means the current moment will be used\. Otherwise provide a string in ISO\-8601(7) format (which must end with a Z)\. Seconds are optional, plus even more optional precision after a decimal\. The default is 3 digit precision, i\.e\. milliseconds\.
.
.P
Besides the \fIutc\fR semi\-convenience, this \fIut\fR array of time fragments will be passed on directly to the \fBswe\.utc_to_jd\fR function (as its arguments)\. It takes precedence over any \fIutc\fR value that it is otherwise derived from\. Such option exists in case an intermediate conversion is not wanted\.
.
.P
Given \fIgeo\fR location with its \fIlat\fR / \fIlon\fR coordinates such as \fB"geo": { "lat": 43\.2166667, "lon": 27\.9166667 }\fR means there can and will be angles (e\.g\. Asc / Mc) keyed as \'3\'\. These come from the \fBswe\.houses\fR function, however there may or may not be house cusps in the final results output \- read about the next option\.
.
.P
A value of false for the \fIhouses\fR means we are not interested in any cusps, rendering any house system irrelevant (for the particular request)\. None will be returned, even if the prerequisite geo coordinates are provided\. Check the swiss ephemeris manual for a list of valid house system codes\. Anyway, the 12 cusps array would be keyed as \'4\'\.
.
.P
An object of various predefined \fBwhat\fR (0 or more) hashed things \- e\.g\. \fB"extra": {"<what>": {<with\-optional\-config>}}\fR\. The config of these is ignored, for now \- as if \fB{}\fR\. There could be some with settings later\.\.\. So, this asks for extra info \- to be keyed as \'0\' in the response, directly corresponding to any of the following \fBwhat\fR(s):
.
.IP "\(bu" 4
"re" \- regarding a copy of the current input settings \- this request
.
.IP "\(bu" 4
"times" \- to be implemented for performance metrics [\fIstart\-time\fR, \fIend\-time\fR]
.
.IP "" 0
.
.SS "Out"
The corresponding sample of precious response:
.
.IP "" 4
.
.nf

{"1": {"0": {"0": 98\.70827783123845}, "1": {"0": 238\.13984880619816}}}
.
.fi
.
.IP "" 0
.
.SH "ALSO"
precious(1), JSON(7), ISO\-8601(7)
.
.SH "HOME"
Index(7), Base(7)
