.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PRECIOUS" "1" "May 2012" "" ""
.
.SH "NAME"
\fBprecious\fR \- a minimum kind of ephemeris
.
.SH "SYNOPSIS"
\fBprecious\fR runs \fBman precious\fR (which is this help)
.
.P
\fBprecious json\fR \- a synonym for \fBman precious\-json\fR
.
.P
\fBprecious <\'{input}\'>\fR json input, even if just {}
.
.P
\fBprecious \-i <file>\fR a json file (relative path)
.
.SH "DESCRIPTION"
Anything less we couldn\'t do astrology with\.
.
.P
Use eden(1) for a better cli experience\.
.
.SH "SEE ALSO"
precious\-json(7), gravity(6), eden(1)
.
.SH "NAVIGATE"
Index(7), Home(7)
