.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PRECIOUS" "1" "July 2012" "" ""
.
.SH "NAME"
\fBprecious\fR \- a minimum kind of ephemeris
.
.SH "ABOUT"
Anything less we couldn\'t do astrology with\.
.
.P
Use eden(1) for a better cli experience\. Better for both precious\-json(7) input options and human\-readable output\. Either of which could be used individually as well\. See \fIstream\fR examples / usage next\.
.
.SH "USAGE"
Running precious from the command line (instead of programming JavaScript) is not the most efficient nor the most convenient, though it\'s ok too\. The commands can tab\-complete\.
.
.P
Some precious\-json(7) must be provided in one of three ways:
.
.IP "1." 4
\fB\-\fR, \fBs\fR or \fBstream\fR input though unix pipes \- all the rest can be covered with this approach too, see the double examples for equivalents\.
.
.IP
eden pre | precious \-
.
.IP "2." 4
\fBf\fR or \fBfile\fR followed by a json file \fB<path>\fR
.
.IP
precious f test/io/for/example\.json
.
.IP
cat test/io/for/example\.json | precious \-
.
.IP "3." 4
\fBo\fR or \fBobject\fR given a json string \fB<\'input\'>\fR, even if just \fB{}\fR
.
.IP
precious o {}
.
.IP
echo {} | precious \-
.
.IP "" 0
.
.P
The streams way could do it all, with just a few extra characters typing\. Though perhaps not using Windows\.
.
.P
Here is how \fBeden\fR can help by not only piping input, but also making the output more readable, streams are awesome:
.
.IP "" 4
.
.nf

eden pre | precious \- | eden eat
.
.fi
.
.IP "" 0
.
.P
This is the equivalent of \fBeden know\fR\. Pipe any of the \fBprecious\fR examples into \fBeden eat\fR \- and feast on what could be seen, at least\.
.
.P
A global eden is automatically available through \fBpostinstall\fR\. Go ahead and try it\.
.
.SH "HELP"
This is also a man\-page and can be read with any one of:
.
.IP "" 4
.
.nf

precious
man precious
precious ? 1
.
.fi
.
.IP "" 0
.
.P
Help for precious\-json(7) is also available using these:
.
.IP "" 4
.
.nf

precious help json
man  precious\-json
.
.fi
.
.IP "" 0
.
.P
See Index(7) or \fBprecious ?\fR for the precious README \fIhttps://github\.com/astrolet/precious#readme\fR\.
.
.SH "ALSO"
precious\-json(7), gravity(6), eden(1)
.
.SH "HOME"
Index(7), Base(7)
